//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C971.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C971.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Title is a required field.
        /// </summary>
        internal static string AssessmentTitleRequired {
            get {
                return ResourceManager.GetString("AssessmentTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max of two assessments allowed.
        /// </summary>
        internal static string AssessmentType2Max {
            get {
                return ResourceManager.GetString("AssessmentType2Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type is a required field.
        /// </summary>
        internal static string AssessmentTypeRequired {
            get {
                return ResourceManager.GetString("AssessmentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All course instructor fields are requried.
        /// </summary>
        internal static string CourseInstrRequired {
            get {
                return ResourceManager.GetString("CourseInstrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Status is a required field.
        /// </summary>
        internal static string CourseStatusRequired {
            get {
                return ResourceManager.GetString("CourseStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Title is a required field.
        /// </summary>
        internal static string CourseTitleRequired {
            get {
                return ResourceManager.GetString("CourseTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than 6 courses to a term.
        /// </summary>
        internal static string SixTermsMax {
            get {
                return ResourceManager.GetString("SixTermsMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date cannot be after the end date.
        /// </summary>
        internal static string StartDateEndDateOrder {
            get {
                return ResourceManager.GetString("StartDateEndDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Title is a required field.
        /// </summary>
        internal static string TermTitleRequired {
            get {
                return ResourceManager.GetString("TermTitleRequired", resourceCulture);
            }
        }
    }
}
